"""
feature_extractor.py
--------------------
Extracts numerical features from a URL for phishing detection.
Each feature is documented with its security rationale.

Author : Mohammed Furqan Sajid
Project: Phishing URL Detection using Machine Learning
"""

import re
import urllib.parse


# ── helpers ──────────────────────────────────────────────────────────────────

def _get_domain(url: str) -> str:
    """Return the netloc (host) portion of a URL."""
    try:
        parsed = urllib.parse.urlparse(url)
        return parsed.netloc.lower()
    except Exception:
        return ""


def _get_path(url: str) -> str:
    try:
        return urllib.parse.urlparse(url).path
    except Exception:
        return ""


# ── individual feature functions ─────────────────────────────────────────────

def url_length(url: str) -> int:
    """
    Phishing URLs tend to be long to hide the real destination.
    Legitimate sites rarely exceed 75 characters.
    """
    return len(url)


def has_ip_address(url: str) -> int:
    """
    Phishing pages often use raw IP addresses instead of domain names
    to avoid registration paper trails.
    Returns 1 if an IP is found in the URL, else 0.
    """
    ip_pattern = re.compile(
        r"(([01]?\d\d?|2[0-4]\d|25[0-5])\.){3}([01]?\d\d?|2[0-4]\d|25[0-5])"
    )
    return 1 if ip_pattern.search(url) else 0


def count_dots(url: str) -> int:
    """
    Excessive dots indicate subdomain abuse used to make URLs look legitimate.
    Example: paypal.com.attacker.com — 3 dots, confusing to users.
    """
    return url.count(".")


def has_at_symbol(url: str) -> int:
    """
    The '@' symbol in a URL causes browsers to ignore everything before it.
    Example: http://legit.com@phishing.com loads phishing.com — a classic trick.
    """
    return 1 if "@" in url else 0


def has_double_slash_redirect(url: str) -> int:
    """
    '//' appearing after the 7th character signals a redirect attempt.
    Attackers use this to disguise the real destination.
    """
    return 1 if url.rfind("//") > 6 else 0


def has_hyphen_in_domain(url: str) -> int:
    """
    Hyphens in domain names are rarely used by legitimate brands.
    Common in typosquatting: payp-al.com, face-book.com.
    """
    domain = _get_domain(url)
    return 1 if "-" in domain else 0


def count_subdomains(url: str) -> int:
    """
    Legitimate sites typically have 1–2 subdomains.
    Phishing pages stack subdomains to appear trustworthy:
    secure.login.paypal.com.attackersite.com
    """
    domain = _get_domain(url)
    parts = domain.split(".")
    return max(0, len(parts) - 2)


def has_https(url: str) -> int:
    """
    Returns 1 if the URL uses HTTPS, 0 otherwise.
    Note: HTTPS alone does NOT guarantee legitimacy — phishers also use SSL.
    Combined with other features it still adds signal.
    """
    return 1 if url.lower().startswith("https") else 0


def path_length(url: str) -> int:
    """Long, complex paths are often used to obscure phishing destinations."""
    return len(_get_path(url))


def count_special_chars(url: str) -> int:
    """
    Count suspicious characters: %, =, &, ?, #
    Phishing URLs pack in query params and redirects.
    """
    return sum(url.count(c) for c in ["%", "=", "&", "?", "#"])


def has_suspicious_words(url: str) -> int:
    """
    Many phishing pages include trust-baiting keywords in the URL.
    Words like 'login', 'secure', 'verify', 'update', 'bank', 'confirm'
    are common in credential-harvesting pages.
    """
    suspicious = [
        "login", "signin", "verify", "secure", "update", "confirm",
        "account", "banking", "password", "credential", "paypal",
        "ebay", "amazon", "apple", "google", "microsoft", "support",
        "webscr", "free", "lucky", "bonus", "winner"
    ]
    url_lower = url.lower()
    return 1 if any(word in url_lower for word in suspicious) else 0


def domain_length(url: str) -> int:
    """Unusually long domain names are a phishing signal."""
    return len(_get_domain(url))


def has_port(url: str) -> int:
    """
    Legitimate websites rarely expose non-standard ports in their URL.
    Example: http://bank.com:8080/login is suspicious.
    """
    try:
        port = urllib.parse.urlparse(url).port
        return 1 if port and port not in (80, 443) else 0
    except Exception:
        return 0


def count_digits_in_domain(url: str) -> int:
    """
    Domains with many digits are often auto-generated by phishing kits.
    Example: 192secure3login.com
    """
    domain = _get_domain(url)
    return sum(c.isdigit() for c in domain)


# ── main extractor ───────────────────────────────────────────────────────────

FEATURE_NAMES = [
    "url_length",
    "has_ip_address",
    "count_dots",
    "has_at_symbol",
    "has_double_slash_redirect",
    "has_hyphen_in_domain",
    "count_subdomains",
    "has_https",
    "path_length",
    "count_special_chars",
    "has_suspicious_words",
    "domain_length",
    "has_port",
    "count_digits_in_domain",
]

_EXTRACTORS = [
    url_length,
    has_ip_address,
    count_dots,
    has_at_symbol,
    has_double_slash_redirect,
    has_hyphen_in_domain,
    count_subdomains,
    has_https,
    path_length,
    count_special_chars,
    has_suspicious_words,
    domain_length,
    has_port,
    count_digits_in_domain,
]


def extract_features(url: str) -> list:
    """
    Run all feature extractors on a single URL.

    Parameters
    ----------
    url : str
        The URL to analyse.

    Returns
    -------
    list
        A list of 14 numerical feature values in FEATURE_NAMES order.
    """
    return [fn(url) for fn in _EXTRACTORS]


def extract_features_batch(urls: list) -> list:
    """
    Extract features for a list of URLs.

    Parameters
    ----------
    urls : list[str]

    Returns
    -------
    list[list]
        2-D list: rows = URLs, cols = features.
    """
    return [extract_features(url) for url in urls]
